function RunTCM_Script_VL_2025(i)
% RunTCM_Script_VL_2025
%
% Top-level pipeline for fitting a conductance-based thalamo-cortical neural
% mass model (TCM) to M/EEG cross-spectral data using a transfer-function
% formulation and Variational Laplace optimisation.
%
% OVERVIEW
% -------------------------------------------------------------------------
% This script implements a full Dynamic Causal Modelling (DCM)-style
% workflow for electrophysiological data, specialised to the thalamo-
% cortical model described in Shaw et al. (2020, NeuroImage). Rather than
% simulating the model purely in the time domain with brute-force numerical
% integration, this version uses local linearisation of the nonlinear state
% equations around a fixed point and evaluates the system in the Laplace /
% frequency domain via a numerical transfer function.
%
% In broad terms, the pipeline is:
%
%   1) Load and prepare M/EEG spectral data
%   2) Specify a thalamo-cortical generative model and connectivity pattern
%   3) Set model priors and initial operating point
%   4) Search for a stable fixed point of the neural mass equations
%   5) Linearise the model around that operating point
%   6) Compute a delay-aware transfer function in the frequency domain
%   7) Compare predicted and observed spectra
%   8) Optimise model parameters using Variational Laplace in generalised
%      coordinates (thermodynamic / free-energy based scheme)
%   9) Save fitted posteriors, predictions, and diagnostics into a DCM struct
%
%
% MODEL
% -------------------------------------------------------------------------
% The underlying generative model is a conductance-based thalamo-cortical
% neural mass model, implemented here with:
%
%   DCM.M.f = @atcm.tc_hilge2
%
% The model describes the evolution of hidden neuronal states x under
% parameters P and exogenous input u:
%
%   dx/dt = f(x,u,P,M)
%
% with observed electrophysiological output y generated by a weighted readout
% of hidden states after linearisation. The model can accommodate intrinsic
% and extrinsic connectivity, multiple neuronal populations per source, and
% biophysically interpretable parameters such as synaptic gains, time
% constants, channel / conductance terms, and observation weights.
%
% In this example a simple one-node model is used, but the same framework
% generalises to larger multi-node thalamo-cortical circuits with forward,
% backward, and lateral connectivity.
%
%
% DATA PREPARATION
% -------------------------------------------------------------------------
% The script expects a text file listing SPM-format electrophysiology
% datasets. These datasets are read, converted into DCM-compatible spectral
% form, and prepared for cross-spectral density (CSD) analysis.
%
% Key preparation steps include:
%   - selection of trials / conditions
%   - definition of channels and source labels
%   - restriction to a chosen frequency range
%   - spectral estimation and optional smoothing
%   - construction of the DCM.xY structure
%
% The helper function:
%
%   atcm.fun.prepcsd
%
% is used to prepare the observed spectra and associated metadata.
%
%
% TRANSFER FUNCTION FORMULATION
% -------------------------------------------------------------------------
% A central feature of this script is the use of a numerical Laplace-domain
% transfer function instead of direct time-domain simulation during fitting:
%
%   DCM.M.IS = @atcm.fun.Alex_LaplaceTFwDNew
%
% This routine:
%
%   - takes the nonlinear neural mass model
%   - evaluates / refines its operating point
%   - linearises the dynamics around the current state estimate
%   - constructs the state Jacobian A, input Jacobian B, and observation
%     mapping
%   - incorporates propagation delays in the frequency domain
%   - computes the frequency response of the model over the frequencies of
%     interest
%
% Conceptually, the nonlinear dynamics are approximated locally as:
%
%   dx/dt ≈ A x + B u
%
% and the spectral response is computed using a delay-aware resolvent of the
% form:
%
%   H(s) = C * (sI - A_eff(s))^(-1) * B
%
% where A_eff includes phase shifts induced by delays. This provides an
% efficient way to predict spectra, cross-spectra, and source-wise responses
% without repeatedly integrating the full nonlinear system over long time
% windows.
%
% This approach is especially useful for fitting resting-state or oscillatory
% electrophysiological data where the key observables are spectral rather
% than trial-wise time-domain responses.
%
%
% PRIORS AND PARAMETERISATION
% -------------------------------------------------------------------------
% Model priors are set using:
%
%   DCM = atcm.parameters(DCM,Ns)
%
% and then manually adjusted for selected parameter groups. These priors
% define the expected values (pE) and prior covariance / precision structure
% (pC) over parameters such as:
%
%   - observation weights (J)
%   - synaptic or conductance terms
%   - delay / smoothing terms (d)
%   - channel / source scaling terms (L)
%   - connectivity and other biophysical constants
%
% Priors can be tightened or loosened to stabilise inference, suppress
% unwanted parameter families, or bias the model toward biologically
% plausible regimes.
%
%
% FIXED POINT / OPERATING POINT SEARCH
% -------------------------------------------------------------------------
% Before spectral fitting, the script searches for a stable fixed point of
% the nonlinear state equations:
%
%   f(x*,0,P,M) = 0
%
% using:
%
%   atcm.fun.find_fixed_point_robust
%
% This operating point is crucial because the transfer-function
% approximation is built by linearising around it. In effect, the model is
% treated as a locally linear system near the inferred baseline state. A
% good fixed point therefore improves both numerical stability and biological
% plausibility of the fitted spectra.
%
%
% OPTIMISATION
% -------------------------------------------------------------------------
% Parameters are optimised using the custom optimisation / inference wrapper:
%
%   M = aFitDCM(DCM)
%
% followed by:
%
%   M.aloglikVLthermGC
%
% The aFitDCM class wraps the DCM structure into a reduced optimisation
% problem and calls a Variational Laplace routine in generalised
% coordinates. The optimisation estimates the posterior over model
% parameters by maximising a variational free-energy / evidence lower bound
% (ELBO)-like objective under a local Gaussian approximation.
%
% In practical terms, the optimiser:
%
%   - builds a reduced parameter vector from prior means / covariances
%   - evaluates model predictions through the DCM wrapper
%   - computes prediction errors in spectral space
%   - updates posterior means and covariance using local curvature
%   - optionally uses thermodynamic / tempered updates for robustness
%
% The output includes:
%
%   Ep  - posterior parameter means
%   CP  - posterior covariance
%   F   - free energy / objective value
%
% An outer loop optionally refits several times if the current prediction
% remains too far from the data, allowing iterative refinement of the
% operating point and posterior parameters.
%
%
% OUTPUTS
% -------------------------------------------------------------------------
% For each dataset, the fitted DCM structure is saved to disk and contains:
%
%   DCM.Ep      posterior parameter estimates
%   DCM.Cp      posterior covariance
%   DCM.F       free energy / model evidence proxy
%   DCM.pred    predicted spectra / cross-spectra
%   DCM.w       frequency vector
%   DCM.G       transfer-function object / auxiliary output
%   DCM.series  optional reconstructed series and state-space diagnostics
%
% These outputs can then be used for:
%   - model comparison
%   - parameter interpretation
%   - subject-level or group-level inference
%   - posterior predictive checks
%   - mechanistic interpretation of oscillatory biomarkers
%
%
% DEPENDENCIES
% -------------------------------------------------------------------------
% This script requires:
%
%   atcm   - thalamo-cortical modelling package
%   aoptim - optimisation / inference package
%   SPM    - for core DCM/SPM helper functions
%
% Example dependency:
%   atcm: https://github.com/alexandershaw4/atcm
%
%
% NOTES
% -------------------------------------------------------------------------
% - This example is configured for a simple one-node model.
% - The same workflow generalises to larger network models.
% - The transfer-function approach is much faster than brute-force
%   integration for spectral fitting, but depends on a sensible operating
%   point and local linear approximation.
% - Delays are handled in the frequency domain within the custom Laplace
%   transfer-function routine.
% - Priors, parameter families, and state initialisation may need tuning for
%   different datasets or model variants.
%
%
% INPUT
% -------------------------------------------------------------------------
% i : index (or vector of indices) specifying which dataset(s) to fit from
%     the dataset list.
%
%
% AS2020-2025
% Alex Shaw

% EXAMPLE ONE NODE SETUP:
%==========================================================================

% Data & Design
%--------------------------------------------------------------------------
Data.Datasets     = 'NewSZ.txt';%'MeanSZDatasets.txt';%'AllSZNoMerge.txt'; % textfile list of LFP SPM datasets (.txt)
Data.Design.X     = [];                % design matrix
Data.Design.name  = {'undefined'};     % condition names
Data.Design.tCode = [1];               % condition codes in SPM
Data.Design.Ic    = [1];               % channel indices
Data.Design.Sname = {'PBVE'};            % channel (node) names
Data.Prefix       = 'rVL_TFD_TCM_';      % outputted DCM prefix
Data.Datasets     = atcm.fun.ReadDatasets(Data.Datasets);

% Model space - T = ns x ns, where 1 = Fwd, 2 = Bkw
%--------------------------------------------------------------------------
T = [... % this is a 1-node model; nothing to put here...
    0];
F = (T==1);
B = (T==2);
C = [1]';          % input(s)
L = sparse(1,1);

[p]=fileparts(which('atcm.integrate_1'));p=strrep(p,'+atcm','');addpath(p);


% Set up, over subjects
%--------------------------------------------------------------------------
for i = i;%1:length(Data.Datasets)
    
    % Data Naming & Design Matrix
    %----------------------------------------------------------------------
    DCM          = [];
    [fp fn fe]   = fileparts(Data.Datasets{i});
    DCM.name     = [Data.Prefix fn fe];
    
    DCM.xY.Dfile = Data.Datasets{i};  % original spm datafile
    Ns           = length(F);         % number of regions / modes
    DCM.xU.X     = Data.Design.X;     % design matrix
    DCM.xU.name  = Data.Design.name;  % condition names
    tCode        = Data.Design.tCode; % condition index (in SPM)
    DCM.xY.Ic    = Data.Design.Ic;    % channel indices
    DCM.Sname    = Data.Design.Sname; % channel names
    
    
    if exist(DCM.name);
        fprintf('Skipping model %d/%d - already exists!\n( %s )\n',i,length(Data.Datasets),DCM.name);
        continue;
    end
    
    % Extrinsic Connectivity - Model Space
    %----------------------------------------------------------------------
    DCM.A{1} = F;
    DCM.A{2} = B;
    DCM.A{3} = L;
    DCM.B{1} = DCM.A{1} | DCM.A{2};
    DCM.B(2:length(DCM.xU.X)) = DCM.B;
    DCM.C    = C;
    
    % Function Handles
    %----------------------------------------------------------------------
    DCM.M.f  = @atcm.tc_hilge2;               % model function handle
    DCM.M.IS = @atcm.fun.Alex_LaplaceTFwDNew   ;            % Alex integrator/transfer function
    DCM.options.SpecFun = @atcm.fun.Afft;    % fft function for IS
    
    % Print Progress
    %----------------------------------------------------------------------
    fprintf('Running Dataset %d / %d\n',i,length(Data.Datasets));
    
    % Frequency range of interest
    fq =  [1 90];
    
    % Prepare Data
    %----------------------------------------------------------------------
    DCM.M.U            = sparse(diag(ones(Ns,1)));  %... ignore [modes]
    DCM.options.trials = tCode;                     %... trial code [GroupDataLocs]
    DCM.options.Tdcm   = [1 2000];                   %... peristimulus time
    DCM.options.Fdcm   = fq;                    %... frequency window
    DCM.options.D      = 1;                         %... downsample
    DCM.options.han    = 1;                         %... apply hanning window
    DCM.options.h      = 4;                         %... number of confounds (DCT)
    DCM.options.DoData = 1;                         %... leave on [custom]
    %DCM.options.baseTdcm   = [-200 0];             %... baseline times [new!]
    DCM.options.Fltdcm = fq;                    %... bp filter [new!]
    DCM.options.UseButterband = fq;

    DCM.options.analysis      = 'CSD';              %... analyse type
    DCM.xY.modality           = 'LFP';              %... ECD or LFP data? [LFP]
    DCM.options.spatial       = 'LFP';              %... spatial model [LFP]
    DCM.options.model         = 'tc6';              %... neural model
    DCM.options.Nmodes        = length(DCM.M.U);    %... number of modes
    
    DCM.options.UseWelch      = 1010;
    DCM.options.FFTSmooth     = 0;
    DCM.options.BeRobust      = 0;
    DCM.options.FrequencyStep = 1;
    
    DCM.xY.name = DCM.Sname;
    DCM = atcm.fun.prepcsd(DCM);
    DCM.options.DATA = 1 ;

    DCM.xY.y{:}  = atcm.fun.agauss_smooth(abs(DCM.xY.y{:}),1)';
        
    % Subfunctions and default priors
    %----------------------------------------------------------------------
    DCM = atcm.parameters(DCM,Ns);
            
    % other model options
    %----------------------------------------------------------------------
    DCM.M.solvefixed=0;      % 
    DCM.M.x = zeros(1,8,7);  % init state space: ns x np x nstates
    DCM.M.x(:,:,1)=-70;      % init pop membrane pot [mV]
        
    load([p '/newpoints3.mat'],'pE','pC')

    pE = spm_unvec(spm_vec(pE)*0,pE);

    pC.ID = pC.ID * 0;
    pC.T  = pC.T *0;
    
    pE.J = pE.J-1000;    
    %pE.J(1:8) = log([.6 .8 .4 .6 .4 .6 .4 .4]);
    pE.J(1:8) = log([.2 .99 .1 .8 .1 .2 .05 .1]);
    %pC.ID = pC.ID + 1/8;
    pE.L = 0;
    pC.a = pC.a*0;

    pE.Gb = pE.H;
    pC.Gb = [1   0   0   0   0   0   0   0;
             0   1   1   0   0   0   0   0;
             0   0   1   0   0   0   0   0;
             0   0   0   1   1   0   0   0;
             0   0   0   0   1   0   0   0;
             0   0   0   0   1   1   0   0;
             0   0   0   0   0   0   0   0;
             0   0   0   0   0   0   1   0]/64;

    %pC.J(1:8)=1/8;
    pC.d(1) = 1/8;
    pC.d(3) = 1/8;


    % Make changes here;
    %-----------------------------------------------------------
   
    DCM.M.pE = pE;
    DCM.M.pC = pC;

    % Optimise using AO.m -- a Newton scheme with add-ons and multiple
    % objective functions built in, including free energy
    %----------------------------------------------------------------------
    w   = DCM.xY.Hz;
    Y   = DCM.xY.y{:};
    DCM.M.y  = DCM.xY.y;
    DCM.M.Hz = DCM.xY.Hz;

    ppE = DCM.M.pE;
    ppC = DCM.M.pC;

    fprintf('--------------- STATE ESTIMATION ---------------\n');
    fprintf('Search for a stable fixed point\n');

    xx = load([p '/newx.mat']); DCM.M.x = spm_unvec(xx.x,DCM.M.x);
    load('init_14dec','x');
    DCM.M.x = spm_unvec(x,DCM.M.x);

    x = atcm.fun.find_fixed_point_robust(DCM.M.pE,DCM.M,1e-10);
    DCM.M.x = spm_unvec(x,DCM.M.x);

    norm(DCM.M.f(DCM.M.x,0,DCM.M.pE,DCM.M))

    fprintf('Finished...\n');
    
          
    fprintf('--------------- PARAM ESTIMATION ---------------\n');
    %fprintf('iteration %d\n',j);

    % Fit with DCM VB routine:
    %----------------------------------------------------------------------
    %[Qp,Cp,Eh,F] = spm_nlsi_GN(DCM.M,DCM.xU,DCM.xY);
    

    % Fit with LM (Log Likelihood estimation):
    %----------------------------------------------------------------------
    M = aFitDCM(DCM)

    M.aloglikVLthermGC;
    M.update_parameters(M.Ep)

    [y,w,G,s] = feval(DCM.M.IS,spm_unvec(M.Ep,DCM.M.pE),DCM.M,DCM.xU);

    numit = 0;
    while cdist(DCM.xY.y{:}',y{:}') > (1/2) && numit < 8
        numit = numit + 1;
        %M.aloglik;
        M.aloglikVLthermGC;
        %M.aloglikFE;
        M.update_parameters(M.Ep);
        [y,w,G,s] = feval(DCM.M.IS,spm_unvec(M.Ep,DCM.M.pE),DCM.M,DCM.xU);
    end
    
    Qp = spm_unvec(M.Ep,DCM.M.pE);
    Cp = M.CP;
    F  = M.F;


    % Fit with LM (Free energy estimation):
    %----------------------------------------------------------------------
    % M = aFitDCM(DCM)
    % 
    % M.aloglikFE
    % M.update_parameters(M.Ep)
    % M.aloglikFE
    % M.update_parameters(M.Ep)
    % M.aloglikFE
    %Qp = spm_unvec(M.Ep,DCM.M.pE);
    %Cp = M.CP;


    % save in DCM structures after optim 
    %----------------------------------------------------------------------
    DCM.M.pE = ppE;
    DCM.Ep = Qp;%spm_unvec(M.Ep,DCM.M.pE);
    DCM.Cp = Cp;

    DCM.M.sim.dt  = 1./600;
    DCM.M.sim.pst = 1000*((0:DCM.M.sim.dt:(2)-DCM.M.sim.dt)');

    [y,w,G,s] = feval(DCM.M.IS,DCM.Ep,DCM.M,DCM.xU);

    DCM.pred = y;
    DCM.w = w;
    DCM.G = G;
    DCM.series = s;
    
    %DCM.Cp = atcm.fun.reembedreducedcovariancematrix(DCM,M.CP);
    %DCM.Cp = makeposdef(DCM.Cp);
    DCM.F  = F;%M.FreeEnergyF;
    %DCM.Cp = M.CP;
    save(DCM.name); close all; clear global;
    
end

end
