function y0 = f2sr(f0,dt)
% Offline conversion of the firing probability ( cumulative distribution
% function spm_Ncdf_jdw.m ) to firing rate, using the explanation in Dayan
% textbook:
% 
% An alternative formulation of a firing-rate model can be constructed...
% Action potentials are generated by the synaptic current through its 
% effect on the membrane potential of the neuron. Due to the membrane 
% capacitance and resistance, the membrane potential is, roughly speaking, 
% a low-pass filtered version of Is (see the Mathematical Appendix). For 
% this reason, the time-dependent firing rate is often modeled as a low-pass 
% filtered version of the steady-state firing rate
%
% r*(dv/dt) = -v+F(w,u)
%
% The constant Tr in this equation determines how rapidly the firing rate 
% approaches its steady-state value for constant Is, and how closely v can 
% follow rapid fluctuations for a time-dependent Is(t). Equivalently, it 
% mea- sures the time scale over which v averages F(Is(t)). The low-pass 
% filtering effect of equation 7.7 is described in the Mathematical Appendix
% in the context of electrical circuit theory. The argument we have used to 
% moti- vate equation 7.7 would suggest that ?r should be approximately equal
% to the membrane time constant of the neuron. However, this argument really 
% applies to the membrane potential, not the firing rate, and the dynamics
% of the two are not the same. Some network models use a value of ?r that 
% is considerably less than the membrane time constant. 


% f = cells by samples, firing
if ndims(f0) == 3
    [ns,nc,nsmp] = size(f0);
else
    ns = 1;
    [nc,nsmp] = size(f0);
    f1(1,:,:) = f0;
    f0        = f1;
end

for j = 1:ns
    for n = 1:nc
        x = squeeze(f0(j,n,:));

        % Tr*(dv/dt) = -v+F(w,u)
        %-------------------------

        y(1)  = x(1);
        for i = 2:length(x)
            %dv  = (-v(i)   + v(i+1) )/ dt 
            y(i) = (-x(i-1) + x(i))./dt;
        end

        s    = y < 0;
        y(s) = -y(s); 

        y0(j,n,:) = y;

    end
end

% I am using Tr == dt

% The constant Tr in this equation determines how rapidly the firing rate 
% approaches its steady-state value for constant Is, and how closely v can 
% follow rapid fluctuations for a time-dependent Is(t). Equivalently, it 
% mea- sures the time scale over which v averages F(Is(t)). The low-pass 
% filtering effect of equation 7.7 is described in the Mathematical Appendix
% in the context of electrical circuit theory. The argument we have used to 
% moti- vate equation 7.7 would suggest that ?r should be approximately equal
% to the membrane time constant of the neuron. However, this argument really 
% applies to the membrane potential, not the firing rate, and the dynamics
% of the two are not the same. Some network models use a value of ?r that 
% is considerably less than the membrane time constant. 